[application]

name = "starwars-server"
version = "0.0.1"
authors = ["Derrick J. Wippler <thrawn01@gmail.com>"]

[dependencies]
"github.com/Sirupsen/logrus" = ""
"github.com/jessevdk/go-flags" = ""
"github.com/julienschmidt/httprouter" = ""
"github.com/justinas/alice" = ""
"github.com/oxtoacart/bpool" = ""
"gopkg.in/throttled/throttled.v2" = ""
"gopkg.in/throttled/throttled.v2/store/memstore" = ""

